### ISSUE TITLE
Tags issues

### ISSUE THREAD

**Issue by Johanna-hub** [Johanna-hub/BrixtonLocal#62]
Now that there are spreadsheets run by different people, some issues arising with tags:

- [ ] Tag text needs to be capitalised - looks messy when it is taken from spreadsheet and is a mixture of cases
- [x] Trim if there is a comma at the end of tag list (this causes an empty tag to display)
- [ ] On the all tags page - they are all lower-case, need to be capitalised
- [x] Look into why there is an empty tag on the tags page in Wokingham and Winchmore Hill
https://www.wokinghamlocal.life/tags
https://www.winchmorehilllocal.life/tags

**Comment by macintoshhelper** [comment]
Trimming (to remove the empty tags) is handled at https://github.com/Johanna-hub/BrixtonLocal/pull/57/files#diff-334d4a183a934c717f95239738394a69R260

**Comment by Johanna-hub** [comment]
ah fab, thanks for letting me know! didn't realise that 😊 You're one step ahead!

**Comment by Johanna-hub** [comment]
Just updated Winchmore Hill and the empty tags still came up when there was a comma at the end of list

**Comment by macintoshhelper** [comment]
I filtered out the falsey tags in the `PlaceItem` component: https://github.com/Johanna-hub/BrixtonLocal/pull/57/files#diff-0a7ed47f39bc6aa89e2431abcd4d4ddcR67

I didn't touch `pages/tags.js` though. Sorry, just realised my previous comment was misleading, I was referring to code that was unrelated.

I haven't tested this locally, but adding `&& tag` to the filter here, to test the truthiness, should fix it:
https://github.com/Johanna-hub/BrixtonLocal/blob/10cdf0ec622e9f96a9622c4947d55cace12917e7/src/pages/tags.js#L33

(also `TagMenuArray` should probably be camel-case, pascal case is generally used for React components or OOP classes – i.e. `<TagMenuArray>` or `new TagMenuArray()`)

Tags are lowercase in the all tags page, but are left alone and generally title case in the home page. I would create a shared `toTagTitleCase` helper function that makes the first letter uppercase, and leaves the rest of the tag alone, or applies a title case function (maybe AP/NYT style with small words kept lower case)

**Comment by Johanna-hub** [comment]
Oh ok, sorry! I completely misunderstood what you meant!  Thanks for the PR will check it out locally and see 😊

**Comment by rb50** [comment]
Just checking in on this issue - I assume the Trim & Empty tags parts are fixed? Before I work on the tag text - should this be fully caps or title case?

**Comment by Johanna-hub** [comment]
There is still this empty tag first on the Winchmore Hill tags page https://www.winchmorehilllocal.life/tags
Not sure why!

Tag Text - capital for first letter of any word - so "Fruit & Veg", "Bread", "Zero-Waste".  Think that looks better!  Both for the tags in each entry and then on the All Tags page.
Thanks so much for looking at it, at the moment I am changing in the spreadsheet!

**Comment by Johanna-hub** [comment]
@rb50 The trim just didn't work for an upload i just did to Brixton!  So hasn't fixed it....

**Comment by macintoshhelper** [comment]
Strange, I added a filter, but maybe the filter is being done too early, before the tags are trimmed. Adding a filter here should fix it I think:
https://github.com/Johanna-hub/BrixtonLocal/blob/358bfbd1f4b8134c1277fbfd905bc30ebe298742/src/pages/tags.js#L33 

And adding a `if (!tag.trim()) { return null; }` here: https://github.com/Johanna-hub/BrixtonLocal/blob/358bfbd1f4b8134c1277fbfd905bc30ebe298742/components/app/Tag.jsx#L261-L263
